### ISSUE TITLE
Author search with synonyms misses results

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/montysolr#20]
A search for an author name which include a first name initial only potentially misses results.  Here is an example and counterexample for this synonym case:

```
BERTA, ZACHORY
BERTA-THOMPSON, ZACHORY
```
1. a query for author:"Berta, Z" misses all records authored by "Berta-Thompson, Zachory K"

```
    "rawquerystring": "author:\"Berta, Z\"",
    "querystring": "author:\"Berta, Z\"",
    "parsedquery": "author:berta, z author:berta thompson, z author:berta thompson, zachory author:berta, zachory author:berta, z* author:berta,",
```
1. whereas a query for author:"Berta, Zachory" works as expected (see use of wildcard):

```
    "rawquerystring": "author:\"Berta, Zachory\"",
    "querystring": "author:\"Berta, Zachory\"",
    "parsedquery": "author:berta thompson, zachory author:berta thompson, zachory * author:berta thompson, z author:berta thompson, z * author:berta thompson, author:berta, zachory author:berta, zachory * author:berta, z author:berta, z * author:berta,",
```

**Comment by aaccomazzi** [comment]
Similarly, a query of "Berta, Zachory K" misses papers by "Berta-Thompson, Zachory K" because synonyms are not being used in this case.  Problem of curation or synonym manipulation by the search engine?
```
author:"Berta, Zachory K" bibcode:2014arXiv1409.0891I
```

**Comment by aaccomazzi** [comment]
Other useful test cases:
```
author:"merchant boesgaard, ann m"
author:"merchant boesgaard, ann"
author:"merchant boesgaard, a"
```
compare with the searches for its synonym:
```
boesgaard, ann m; merchant boesgaard, ann m
```

**Comment by romanchyla** [comment]
another use cases:

```
pustilnik, s vs. pustil'nik, s (and O'Brians of the world)
```

**Comment by romanchyla** [comment]
This is *actually* by design, if we move in the direction of 'fixing it', we'll break some other behaviour

Let's say the synonym file lists those entries:

```
berta thompson, zachory; berta, zachory
doe, joe;foe, joe
```

the query parser works in the following way:

input= ```John Doe```

 1. normalizes input (doe, j)
 2. creates possible variations (doe, j)
 3. discovers synonyms *using both* the original input and the variations (result is: doe, joe; doe,j; foe, joe)
 4. *removes the variations* because they were only used to find the possible synonyms (doe, joe; foe, joe)
 5. ...adds transliterations, variations, more synonyms, shake, repeat...drink


the criticial logic is in step 3 and 4 - the desire is to *find as many synonyms as possible, BUT ONLY IFF curators wanted them to be found*. If we introduce the automatic expansion, we'll take that power from them. 

 1) If curators wanted to distinguish ```Berta, Zachory``` from ```Berta, Zeta``` they need to use the following synonyms:
```
berta, zeta; berta-thompson, zeta
berta, zachory; berta-thompson, zachory
berta, z; berta-thomson, z
```

 2) if they don't care to distinguish these two names, this will do the trick


```
berta, zeta; berta-thompson, zeta; berta, z
berta, zachory; berta-thompson, zachory; berta, z
```

imagine these situations, you search for:

  1. ```berta, zeta```
    1) gets  ```berta, zeta; berta, z; berta-thompson, zeta; berta, z``` but NOT zachory (correct)
    2) gets ```berta, zachory``` (which is *wrong*)

  2. ```berta, z```
   1) gets: ```berta, z; berta-thompson, z``` (but ignores ```berta, zeta; berta, zachory``` - that is a correct bahaviour, they will be found thanks to ```berta, z*``` expansion)
   2) gets: ```berta, z; berta-thompson, z; berta, zeta; berta, zachory...``` (correct; but unnecessary)

  3. ```berta-thompson, zeta```
   1) gets: ```berta, z; berta-thomson, z;....``` (but not ```berta-thompson, zachory```; correct)
   2) gets: ```berta-thompson, zachory``` (*wrong*)


The current synonym file has only this entry:
```
berta thompson, zachory; berta, zachory
```

but to work as you expect, it needs to become:

```
berta thompson, zachory; berta, zachory
berta thompson, z; berta, z
```


---
in the case of ```boesgaard, a m``` not finding ```merchant boesgaard, a m``` it is again synonym file; IFF the synonym file contained only initials, then it would work, ie

```
boesgaard, a; boesgaard, a m; merchant boesgaard, a m; merchant boesgaard, a
```

BUT AGAIN, this depends... IFF we (in the future) want to distinguish 'ann marie' from 'anne michele', it needs two rows

---

```
pustilnik, s vs. pustil'nik, s (and O'Brians of the world)
```

The parser correctly recognizes the apostrophe, but ```o'brian``` will be **normalized** as ```o brian```; maybe this is incorrect - do we want ```obrian``` ? ...maybe, but again - if we do that, there will be no way to distinguish ```o'brian``` from ```obrian``` (assuming they are two different names!)

otherwise, synoym rules know nothing about ```pustulnik``` nor ```o'brian``` - so I think it is the same case

To conclude: please review what I wrote, but to me it seems like a case of missing synonym rules. 

Recommendations:
 1. use acronyms instead of full names (ie. "berta-thompson, z" instead of "berta-thompson, zachory")
 2. when two "zachory" need to be distinguished, use full names and always make sure the *short form* is on separate line
 3. list all combinations of given names (but only those that can be used; ie there are 8 permutations of 'anne marie cecilie' - but people use names in their order: ie. ```a m c``` and not ```c m a```); but curators are free to use any form/combination (```a m c; a c; a m; a; m; c```)

btw: that last point about combinations and permutations should convince you that if we try to ```guess``` short-hand rules automatically, we will be generating many *unnecessary* search patterns

**Comment by csgrant00** [comment]
Does this mean we should revert back to the version of the synonym file without full name expansion? 
(/proj/ads/abstracts/config/author.syn)

**Comment by aaccomazzi** [comment]
Not if I can help it!  Let's talk about this tomorrow when we're all in the
office.

-- AA

On Tue, Mar 17, 2015 at 9:37 AM, Carolyn Grant <notifications@github.com>
wrote:

> Does this mean we should revert back to the version of the synonym file
> without full name expansion?
> (/proj/ads/abstracts/config/author.syn)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/romanchyla/montysolr/issues/20#issuecomment-82356402>.
>



-- 
Dr. Alberto Accomazzi
Program Manager
NASA Astrophysics Data System - http://ads.harvard.edu
Harvard-Smithsonian Center for Astrophysics - http://www.cfa.harvard.edu
60 Garden St, MS 83, Cambridge, MA 02138, USA

**Comment by romanchyla** [comment]
The full name is there to distinguish one person from another person of the same surname. When there is no such person (ie. and no need to distinguish two persons); then short name is preferred
