### ISSUE TITLE
Add ack field to unfielded search

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/montysolr#34]
An unfielded query currently is rewritten into a query over the following fields:
abstract, body, author, first_author, title, keyword, keyword_norm, and all

We should add 'ack' to the list.  Incidentally, I don't quite understand where this is defined.  I thought it would be in https://github.com/romanchyla/montysolr/blob/master/contrib/examples/adsabs/solr/collection1/conf/solrconfig.xml#L660
but the list does not reflect what I see via the SOLR debugger.

**Comment by romanchyla** [comment]
is this really necessary? I'm asking because the list of unfielded search indexes is rather large (and with every addition we are pushing the penalty thorn deeper) - recall that for some situations, the unfielded search gets expanded exponentially - ie. innocuious "foo bar" could generate Nx3 queries where N is the field list, each of which has its own interna parsing; resulting in Nx4 large final query

**Comment by aaccomazzi** [comment]
It is necessary but maybe we can get the desired outcome in a different way: why don't we simply do a copyfield of ack to all?  Come to think of it, I'm surprised it's not indexed there already...
